# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-03-14 13:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usertimesheets', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='create_at',
            new_name='created_at',
        ),
    ]
